const express = require('express');
const router = express.Router();
// var multipart = require('connect-multiparty');
const passport = require('passport');
const userAuthenticationController = require('../controllers/userAuthenticationController');
const userDashboardController = require('../controllers/userDashboardController');
const userInfoController = require('../controllers/userInfoController');
const userSillTagController = require('../controllers/userSkillTagController');
const userSocialButtonController = require('../controllers/userSocialButtonController');
const userEducationController = require('../controllers/userEducationController');
const userExperienceController = require('../controllers/userExperienceController');
const userTimelineController = require('../controllers/userTimelineController');
const decodeToken = require('../middlewares/decodeToken');
const fileController = require('../controllers/fileController');
const uploadMiddleware = require('../middlewares/uploadFiles');
const userInfoTagController = require('../controllers/userInfoTagController');
const passportCallback = require('../classes/PassportCallback');
const AuthMiddleware = require('../middlewares/Authentication');

// var multipartMiddleware = multipart();

router.post('/login',userAuthenticationController.post);
router.get('/verifyuser',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}),userAuthenticationController.get)
router.get('/getallfiles',decodeToken.decodeToken,passport.authenticate('jwt',{session:false}),fileController.getAllFiles);
router.post('/uploadfiles',decodeToken.decodeToken, passport.authenticate('jwt',{session:false}) ,uploadMiddleware.uploadHandlerImg);
router.post('/uploadresume',decodeToken.decodeToken, passport.authenticate('jwt',{session:false})  ,uploadMiddleware.uploadHandlerPDF);
router.post('/deletefiles',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,fileController.deleteFiles);
router.get('/dashboard',decodeToken.decodeToken, passport.authenticate('jwt',{session:false})  ,userDashboardController.get);
router.post('/userinfoedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userInfoController.post);
router.post('/userinfotagedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userInfoTagController.editPost);
router.post('/userinfotagadd',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userInfoTagController.addPost);
router.post('/userinfotagdelete',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userInfoTagController.delete);
router.post('/userskilltagedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userSillTagController.editPost);
router.post('/userskilltagreorder',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userSillTagController.UpdateSkillPost);
router.post('/userskilltagadd',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userSillTagController.addPost);
router.post('/userskilltagdelete',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userSillTagController.delete);
router.post('/usereducationedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userEducationController.editPost);
router.post('/usereducationreorder',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userEducationController.ReorderPost);
router.post('/usereducationadd',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userEducationController.addPost);
router.post('/usereducationdelete',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userEducationController.delete);
router.post('/userexperienceedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userExperienceController.editPost);
router.post('/userexperiencereorder',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userExperienceController.ReorderPost);
router.post('/userexperienceadd',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userExperienceController.addPost);
router.post('/userexperiencedelete',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userExperienceController.delete);
router.post('/usersocialbuttonedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userSocialButtonController.editPost);
router.post('/usersocialbuttonadd',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userSocialButtonController.addPost);
router.post('/usersocialbuttondelete',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userSocialButtonController.delete);
router.post('/usertimelineedit',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userTimelineController.editPost);
router.post('/usertimelineadd',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false}) ,userTimelineController.addPost);
router.post('/usertimelinedelete',decodeToken.decodeToken,  passport.authenticate('jwt',{session:false})  ,userTimelineController.delete);
router.post('/register',  userAuthenticationController.register);
router.get('/activateuser',userAuthenticationController.activateUser);

module.exports = router;